### ISSUE TITLE
Slash in DN

### ISSUE THREAD

**Issue by martin-jelen** [dnknth/ldap-ui#31]
Hi,

the tree browsing feature seems to not work correctly when the DN contains slashes.

I have an example structure with the following DN: node=dc/3dab,ou=detail,o=entitlements". The use of slashes may seem to not be a good idea, however I'm not in charge of the schema.

It seems to work for /api/entry/node=dc/3dab,ou=detail,... (when searching for the node) but it doesn't when browsing.

There might be 2 different but related problems:

- when I click on the "unfold" icon, a request to the backend gets sent and ends with a 404: 
`[07/Jul/2022:11:50:09 +0000] "GET /api/tree/node=dc/3dab,ou=detail,o=entitlements 1.1" 404 207 ...`
- when I click on the name of the node with a slash in in, no request ist sent to the backend. That seems to be related to TreeView.vue ("item" is undefined):
`const item = this.tree.find(dn);
 if (item.hasSubordinates && !item.open) await this.toggle(item);`

That's how far I got, but I'm not able to fix the issue myself, maybe you have a clue about what's going wrong there?

Kind Regards
Martin Jelen

**Comment by dnknth** [comment]
Hello @martin-jelen,

Oh my, this is going to be tricky. Slashes in RDNs don't agree too well with the app's URL structure. Will take a moment to address this design flaw.

**Comment by dnknth** [comment]
Hello @martin-jelen,

I just pushed a new version on GitHub and a new image on Docker hub with corrections. Please give it a try and let me know whether it works.

**Comment by martin-jelen** [comment]
Hi,

thank you for the fast response and the attempted fix! Now the 404s on the server side are gone, but the UI still doesn't show the tree correctly.

This time I managed to set breakpoints in Firefox to see what's happening. The find() method doesn't seem to be able to find the node which is there (according to the debugger watch window). I can't really debug the minified JS code of the find method, so I don't see the cause for this behavior. See screenshot:

![image](https://user-images.githubusercontent.com/20581704/178306055-11cfda69-84e4-4ff6-9bbe-eee98ac66d09.png)

Kind Regards
Martin Jelen

**Comment by dnknth** [comment]
Hello @martin-jelen,

I cannot over here reproduce it with the demo images. The tree shows correctly, and I can also edit entries in a subtree with slashes in the RDN. Could this be a browser cache issue?

**Comment by dnknth** [comment]
Steps I tried to reproduce:

* Loaded the [Flintstones data](https://github.com/dnknth/ldap-ui/blob/master/docker-demo/flintstones.ldif) into OpenLdap (see [the demo](https://github.com/dnknth/ldap-ui/tree/master/docker-demo))
*  Connected as admin (see LDIF for credentials)
* Renamed `ou=Pets` into `postalcode=12/345`
* Reloaded the tree and opened the renamed node
* Edited one of the child entries

Does this reflect your setup or did I miss something?

**Comment by dnknth** [comment]
Sorry, still no luck over here, it seems to work also with slashed in the RDN of subordinate nodes, see screenshot:

![Bildschirmfoto 2022-07-13 um 11 48 40](https://user-images.githubusercontent.com/41536869/178705174-9249da5c-b3ca-4467-a2f0-b22e57d2d0c3.png)

**Comment by dnknth** [comment]
For easier debugging you can start the UI locally in development mode against the dockerized backend with `npm install && npm run dev`. It then listens on `http://localhost:3000`.

**Comment by dnknth** [comment]
Is this issue still open? Otherwise, please feel invited to close it.
